### ISSUE TITLE
Have an optional cost to /myhead

### ISSUE THREAD

**Issue by bundabrg** [Thatsmusic99/HeadsPlus#14]
### Description of request

Noticed players just changing their skin to get heads they want. It may be useful to have the ability to have a cost associated with using the /myhead command OR being able to buy your own head from the shop.

**Comment by Thatsmusic99** [comment]
Hi - I do believe there is already an option of which can comply with your request, since there is an option which can add player heads to customheads.yml and have them sold in /heads, however it does have a cooldown thanks to Mojang’s API. To manually add a player’s head to /heads, just use /addhead <Player name> and if it succeeds, a new section in the heads GUI will appear called “players”, and have that player’s head in there where it can be bought (Wicked feature was added by jascotty2). Any questions about it let me know!

**Comment by bundabrg** [comment]
Thanks for the reply. I presume though that this would need to be done for each new player? Or would they auto appear when players join?

**Comment by Thatsmusic99** [comment]
Using the command would allow you to directly choose which players you want on the /heads GUI, or using the config options so that the plugin will sort it out for you every time a new player joins: https://github.com/Thatsmusic99/HeadsPlus/wiki/Configuring-config.yml#section-7-autograb

**Comment by bundabrg** [comment]
Thanks for your help and I totally missed that section of the guide. This resolves this issue.
Thanks for a great plugin.
