### ISSUE TITLE
[BUG] MySQL Row size too large?

### ISSUE THREAD

**Issue by Ant4rez** [Thatsmusic99/HeadsPlus#27]
## FIRST-HAND CHECK - ARE YOU USING THE LATEST VERSION/SNAPSHOT OF HEADSPLUS? Have you checked to see if others have submitted the same bug report? 
State here when you have checked the following points above.

### Description of the bug
When i setup in the config to use MySQL at the end of ther server startup appears a mysql warn.

### To Reproduce
1. Config Mysql
2. Start the server
3. See the error.

### Have you been able to reproduce the bug more than once?
Yes.

### Expected behavior
Start the server normally.

### Has a debug report been generated? 
https://hastebin.com/evifaliroz.md

### Required information
- Server version: Paper version git-Paper-99 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
- HeadsPlus version: 6.10.11
- Whether or not the plugin uses MySQL: Yes (MariaDB)
- Server type (e.g Spigot, Paper): Paper
- Uses Vault: Yes

**Comment by Thatsmusic99** [comment]
I don't think I've seen such an issue appear beforehand and the error doesn't seem to make sense considering how tables are set up. Can I ask if any of HP's tables appear in your MySQL database (headspluslb, headsplussh and headspluscraft), and if so, is there any overflowing data inside?

**Comment by Ant4rez** [comment]
The HP's tables doesn't appears on the DB.

**Comment by Thatsmusic99** [comment]
Will attempt to reproduce today, although I can't guarantee a fix with a stable jar because HP is having massive chunks of it rewritten, but if all goes well, the fix will come with that.

**Comment by Thatsmusic99** [comment]
I was not able to reproduce the problem. This was tested using the following:
- HeadsPlus v6.10.11 (latest)
- Paper build 79, then 100 (1.16.1)
- A locally hosted database (InnoDB)
- An externally hosted database (also InnoDB)

**Comment by Thatsmusic99** [comment]
Turns out I've had this discussion with someone already in the past - I asked them to change `innodb_strict_mode` to off. If you're using phpMyAdmin, you'll find it in the Variables section.

MariaDB seems to have made an article on it as well, take a look here for more information: https://mariadb.com/kb/en/troubleshooting-row-size-too-large-errors-with-innodb/

On my locally hosted database, I had strict mode enabled, but on my externally hosted database, it was disabled. I couldn't reproduce the problem on either of them.
