### ISSUE TITLE
[BUG] HeadsPlus causing lag spikes

### ISSUE THREAD

**Issue by cloakfox** [Thatsmusic99/HeadsPlus#38]
Paper 1.16.5
HeadsPlus 6.11.2

https://pastebin.com/F0QD7pFn

**Comment by Thatsmusic99** [comment]
That's more Mojang's authentication services being rubbish and slow.

**Comment by cloakfox** [comment]
I know, we've had the exact same issue with our custom leaderboards plugin, it would still be nice if the plugin doesn't completely spas out though, and lag the whole server.

**Comment by Thatsmusic99** [comment]
I don't think I can do that, and here's a small run-down of as to why.

What the plugin's trying to do is to literally drop the item, and that's it. I can't do anything more than that. What the server's doing internally is trying to load the player's texture onto the skull, and it's doing this by asking for a response from Mojang's servers, which are obviously holding up. It's also doing this on the main thread, which holds up the server. I can't separate it onto a separate thread either because Bukkit is fussy about that and won't allow it.

If it was something like let's say getting an offline player by their name, I would look further into it, but in this scenario there's not much else to be done unless someone can take web requests off the main thread or propose an alternative solution.

**Comment by Thatsmusic99** [comment]
Worst case scenario, I can take a deeper dive into NMS when I get the chance to see if anything specific stops the server from creating web requests (e.g. caching), but I won't be able to do that for a while since I have to get some school coursework done.

**Comment by cloakfox** [comment]
.... Seriously.

How about caching, or fallbacking to a skeleton skull, also bukkit being fussy?? ?I've seen this issue get fixed in multiple projects. There must be a way.

**Comment by cloakfox** [comment]
> Worst case scenario, I can take a deeper dive into NMS when I get the chance to see if anything specific stops the server from creating web requests (e.g. caching), but I won't be able to do that for a while since I have to get some school coursework done.

Is this project fully opensource? I can have one of my go-to devs take a look at it.

**Comment by Thatsmusic99** [comment]
You've probably seen it get fixed if it's involving getting an offline player, I've fixed that easily on multiple occasions. I haven't seen any problems with dropping items before though, that's a new story. Please at least be patient with me.

Yes, it is fully open source, I'll push a few changes first though.
