### ISSUE TITLE
[BUG] Vault problem

### ISSUE THREAD

**Issue by Gurbiel** [Thatsmusic99/HeadsPlus#6]
### Description of the bug
HeadsPlus can't detect vault

### To Reproduce
1. Start server

### Have you been able to reproduce the bug more than once?
Every time I start the server

### Expected behavior
I expect it to hook up  to vault, so I can use /sellhead

### Screenshots
![image](https://user-images.githubusercontent.com/42325931/60762558-9f84d580-a063-11e9-8806-079f4faaa3e3.png)

### Has a debug report been generated? 
https://pastebin.com/EU3ZRcM4

### Required information
- Server version: git-Paper-124 (MC: 1.14.3)
- HeadsPlus version: 6.5.1
- Whether or not the plugin uses MySQL: no, it does not
- Server type (e.g Spigot, Paper): Paper
- Uses Vault: can't really tell, it can't detect vault

## Additional information
I'm using the latest version of vault (1.7.2-b107)
HeadsPlus config file is default (no changes, as generated)
Latest log from console: https://pastebin.com/9BuGeHrJ

**Comment by Thatsmusic99** [comment]
Please do /vault-info. If Economy comes up as null, that means there is no economy plugin which HeadsPlus can actually use. Examples of economy plugins include Essentials and DKCoins.

**Comment by Gurbiel** [comment]
Thank you, with economy installed everything works fine. May I suggest changing the WARN message from "Vault not found!" to "Vault and/or economy not found!"? It may clear things up for others.

**Comment by Thatsmusic99** [comment]
Probably would be a good idea if it wasn’t for the fact I’d have to do some locale changes (which I absolutely hate to mess around with), but will make changes regardless.

**Comment by Gurbiel** [comment]
I know it's the wrong place to ask but do you want a polish translation for headsplus? I could help if you want.

**Comment by Thatsmusic99** [comment]
You sure can, here's an idea of how to do so:

1. Fork the repository, so that you can make changes easily and so that you'd be able to make a pull request to directly push the changes.
2. The file in question which I'd prefer you editing is this one: https://github.com/Thatsmusic99/HeadsPlus/blob/master/MAIN/src/main/java/io/github/thatsmusic99/headsplus/locale/pl_pl.java 
(You can edit messages.yml instead though if you're more comfortable with it, and can send it to me directly via Pastebin or similar).
3. The English translations which you can use are here: https://github.com/Thatsmusic99/HeadsPlus/blob/master/MAIN/src/main/java/io/github/thatsmusic99/headsplus/locale/en_uk.java

Although it's only if you definitely want to, and you don't have a time limit on it either, especially considering I'm unable to make online payments so literally volunteering is a godsend to me. Any questions you have, feel free to ask and I'll answer whilst I can. Thanks again!

**Comment by Gurbiel** [comment]
I have finished with translating (I used the fork method). Can I send it to my friend so he can check for mistakes and correct what's wrong?

**Comment by Thatsmusic99** [comment]
Of course, I have no problem with it!

**Comment by Gurbiel** [comment]
I made a pull request with all lines translated
